name: ultimate_media_player
description: "A complete media player and downloader application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit: any
  media_kit_video: any
  media_kit_libs_android_video: any
  just_audio: any
  screen_brightness: any
  volume_controller: any
  file_picker: any
  path_provider: any
  permission_handler: any
  dio: any
  youtube_explode_dart: any
  http: any

flutter:
  uses-material-design: true
